---
language: java

jdk:
- oraclejdk8

before_install:
  - ls -lthra
  - java -version
  - echo "starting build..."

install:
  - ./build-coatjava.sh

script:
  - ls -lthra
  - which groovy
  - echo "starting unit tests..."
  - cd validation/unit-tests/
  - ./run-unit-tests.sh
  - cd -
  - echo "finished unit tests"
  - cd validation/advanced-tests/
  - ./run-advanced-tests.sh
  - cd -
  - echo "finished advanced tests"
  - mvn cobertura:cobertura # for codecov

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  emails: false
