---

sudo: required

language: java

jdk:
- oraclejdk8

# this affects which java version is used:
#addons:
#  apt:
#    packages:
#      - oracle-java8-installer

before_install:
    - sudo add-apt-repository -y ppa:webupd8team/java
    - sudo apt-get update
    - sudo apt-get install -y oracle-java8-installer || true
#todo remove this kludge and the above || true when the ppa is fixed
    - cd /var/lib/dpkg/info
    - sudo sed -i 's|JAVA_VERSION=8u171|JAVA_VERSION=8u181|' oracle-java8-installer.*
    - sudo sed -i 's|PARTNER_URL=http://download.oracle.com/otn-pub/java/jdk/8u171-b11/512cd62ec5174c3487ac17c61aaa89e8/|PARTNER_URL=http://download.oracle.com/otn-pub/java/jdk/8u181-b13/96a7b8442fe848ef90c96a2fad6ed6d1/|' oracle-java8-installer.*
    - sudo sed -i 's|SHA256SUM_TGZ="b6dd2837efaaec4109b36cfbb94a774db100029f98b0d78be68c27bec0275982"|SHA256SUM_TGZ="1845567095bfbfebd42ed0d09397939796d05456290fb20a83c476ba09f991d3"|' oracle-java8-installer.*
    - sudo sed -i 's|J_DIR=jdk1.8.0_171|J_DIR=jdk1.8.0_181|' oracle-java8-installer.*
    - sudo apt-get update
    - sudo apt-get install -y oracle-java8-installer
    - cd $TRAVIS_BUILD_DIR
    - if [[ $TRAVIS_BRANCH = $TRAVIS_TAG && $TRAVIS_PULL_REQUEST = 'false' && $TRAVIS_BRANCH = 'master' ]]; then openssl aes-256-cbc -K $encrypted_d57b5eec735f_key
      -iv $encrypted_d57b5eec735f_iv -in .travis/secrets.tar.enc -out .travis/local.secrets.tar
      -d; tar xv -C .travis -f .travis/local.secrets.tar; fi

    - ls -lthra
    - java -version
    - echo "starting build..."

install:
  - java -version
  - ./build-coatjava.sh

script:
  - ls -lthra
  - which groovy
  - echo "starting unit tests..."
  - cd validation/unit-tests/
  - ./run-unit-tests.sh
  - cd -
  - echo "finished unit tests"
  - cd validation/advanced-tests/
  - ./run-advanced-tests.sh
  - ./run-eb-tests.sh -100 electronproton
  - ./run-eb-tests.sh -100 electrongamma
  - ./run-eb-tests.sh -100 electronprotonC
  - ./run-eb-tests.sh -100 electronneutronC
  - cd -
  - echo "finished advanced tests"
  - mvn cobertura:cobertura &> /dev/null # for codecov

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  emails: false
